import {Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const Outfitfont = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${Outfitfont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar></Navbar>
        <main className=" mx-auto container">
          {children}
        </main>
        <Footer></Footer>
        </body>
    </html>
  );
}
